DATA_SEG SEGMENT 
	STRING  DB  '???????????$'
DATA_SEG ENDS

CODE_SEG SEGMENT 
	ASSUME	DS:DATA_SEG, CS:CODE_SEG
	LEA	SI, STRING 
	MOV	BX, $0
	JMP	L1
L0:	INC	BX
	INC	SI
L1:	MOV	AL, [SI]
	CMP	AL, '$'
	JNE	L0
EXIT:	MOV	AX, 4C00H
	INT	21H
CODE_SEG ENDS